spring:
  application:
    name: course-unlocker
  profiles:
    active: redis
  session:
    store-type: none
#  output:
#    ansi:
#      enabled: ALWAYS
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${oauth.tokenprovider.url}/.well-known/jwks.json
course-unlocker:
  version: @app.version@
  env: ${app.env}

---

spring:
  profiles: redis
  session:
    store-type: redis
    redis.namespace: course-unlocker-${app.version}:session